name 'newcontext-demo-site'
maintainer 'Brian OConnell'
maintainer_email 'bravtotangooscar@gmail.com'
license 'all_rights'
description 'Installs/Configures newcontext-demo-site'
long_description 'Installs/Configures newcontext-demo-site'
version '0.1.0'
supports 'ubuntu'

depends 'nginx'
depends 'zip'